# Generated by Django 5.1.1 on 2024-09-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentreport',
            options={'verbose_name': 'گزارش حوادث', 'verbose_name_plural': 'گزارش حوادث'},
        ),
    ]
